/* mega_seed.sql ────────────────────────────────────────────
   NIGERIAN POLITICAL DISCOURSE PLATFORM
   LeftPlot.site - Nigerian Politics Focus
------------------------------------------------------------*/

/* ADD USERS - Nigerian Political Personalities & Citizens */
INSERT INTO users (username,email,password,role,created_at,verified) VALUES
  ('tinubu_supporter'    ,'tinubu_fan@demo.com'       ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('peter_obi_fan'       ,'obi_fan@demo.com'          ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('atiku_campaign'      ,'atiku_team@demo.com'       ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('lagos_businessman'   ,'lagos_biz@demo.com'        ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('kaduna_teacher'      ,'kaduna_teach@demo.com'     ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('port_harcourt_youth' ,'ph_youth@demo.com'          ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('kano_trader'         ,'kano_trade@demo.com'       ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('enugu_lawyer'        ,'enugu_law@demo.com'        ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('abuja_civil_servant' ,'abuja_cs@demo.com'         ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('ibadan_student'      ,'ibadan_student@demo.com'    ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('calabar_doctor'      ,'calabar_doc@demo.com'       ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('maiduguri_engineer'  ,'maiduguri_eng@demo.com'    ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('jos_farmer'          ,'jos_farm@demo.com'          ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('sokoto_imam'         ,'sokoto_imam@demo.com'      ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('benin_artist'        ,'benin_art@demo.com'         ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('zaria_professor'     ,'zaria_prof@demo.com'        ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('warri_oil_worker'    ,'warri_oil@demo.com'         ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('bauchi_nurse'        ,'bauchi_nurse@demo.com'      ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('ilorin_taxi_driver'  ,'ilorin_taxi@demo.com'       ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('jalingo_teacher'     ,'jalingo_teach@demo.com'     ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('yola_businesswoman'  ,'yola_biz@demo.com'          ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true);

/* 15 NIGERIAN POLITICAL POSTS - 2027 Election Focus */
INSERT INTO posts (title,slug,content,user_id,created_at) VALUES
  ('Fuel subsidy removal: Na who dey suffer pass?',
   'fuel-subsidy-removal-na-who-dey-suffer-pass',
   'Since Tinubu remove subsidy, my generator no dey work again. Diesel don reach N1,200 per liter. How we go survive like this? Small business owners dey cry everyday. Government dey talk about palliatives but we no see anything. 2027 election go hot o!', 
   (SELECT id FROM users WHERE username = 'lagos_businessman'), NOW() - INTERVAL '6 days'),

  ('Peter Obi 2027: Can he really win this time?',
   'peter-obi-2027-can-he-really-win-this-time',
   'Obi movement still strong but PDP and APC don learn from 2023. They go rig am again? Labour Party need better strategy. We need to register more voters and protect our votes. No be by social media alone. Ground work important!',  
   (SELECT id FROM users WHERE username = 'peter_obi_fan'), NOW() - INTERVAL '5 days'),

  ('Naira devaluation: Rich people dey buy dollars, poor people dey suffer',
   'naira-devaluation-rich-people-dey-buy-dollars-poor-people-dey-suffer',
   'Dollar don reach N1,500. Imported goods don become luxury. Local manufacturers dey close shop. Government dey talk about floating exchange rate but na poor people dey bear the brunt. Rich people dey buy dollars and keep for future. This country hard!',  
   (SELECT id FROM users WHERE username = 'enugu_lawyer'), NOW() - INTERVAL '5 days 3 hours'),

  ('Security situation: Bandits everywhere, government no dey do anything',
   'security-situation-bandits-everywhere-government-no-dey-do-anything',
   'Kaduna, Zamfara, Niger - bandits dey rule. Even Abuja no safe again. Police and army dey collect salary but no dey work. Citizens dey pay ransom with their own money. 2027 election, security go be major issue. Who go solve this wahala?', 
   (SELECT id FROM users WHERE username = 'kaduna_teacher'), NOW() - INTERVAL '4 days'),

  ('Atiku vs Tinubu 2027: Same old story or new chapter?',
   'atiku-vs-tinubu-2027-same-old-story-or-new-chapter',
   'Atiku don contest 4 times, Tinubu don contest 3 times. These old men still want to rule us? Young people need to wake up and take over. We need fresh ideas, not recycled politicians. 2027 must be different!', 
   (SELECT id FROM users WHERE username = 'atiku_campaign'), NOW() - INTERVAL '4 days'),

  ('Minimum wage: N30,000 no fit buy anything again',
   'minimum-wage-n30000-no-fit-buy-anything-again',
   'Food prices don double, transport don double, everything don double but salary still N30,000. How person go survive? Government dey talk about new minimum wage but na talk talk. Workers dey suffer. 2027 election, workers go show them pepper!', 
   (SELECT id FROM users WHERE username = 'abuja_civil_servant'), NOW() - INTERVAL '3 days'),

  ('Education crisis: Our children no dey learn anything',
   'education-crisis-our-children-no-dey-learn-anything',
   'ASUU strike, poor facilities, teachers no dey paid well. Private schools dey charge millions. Government schools no dey work. How our children go compete with other countries? Education must be priority for 2027 candidates.', 
   (SELECT id FROM users WHERE username = 'ibadan_student'), NOW() - INTERVAL '3 days'),

  ('Healthcare system: Hospitals dey kill people more than sickness',
   'healthcare-system-hospitals-dey-kill-people-more-than-sickness',
   'Government hospitals no dey work. Private hospitals dey charge like international rates. Poor people dey die because they no get money for treatment. Health insurance no dey work. 2027 election, healthcare must be on the table!', 
   (SELECT id FROM users WHERE username = 'calabar_doctor'), NOW() - INTERVAL '2 days'),

  ('Corruption: EFCC dey catch small thieves, big thieves dey rule',
   'corruption-efcc-dey-catch-small-thieves-big-thieves-dey-rule',
   'Politicians dey steal billions, EFCC dey catch Yahoo boys. Big thieves dey walk free, small thieves dey go jail. This country no make sense. 2027 election, we need to vote for people with integrity, not thieves!', 
   (SELECT id FROM users WHERE username = 'enugu_lawyer'), NOW() - INTERVAL '2 days'),

  ('Youth unemployment: 50% of graduates no get job',
   'youth-unemployment-50-of-graduates-no-get-job',
   'NYSC dey pay N33,000, graduates dey do okada. Government dey talk about job creation but na talk talk. Young people dey leave Nigeria in droves. Brain drain dey kill our country. 2027 election, youth must demand better!', 
   (SELECT id FROM users WHERE username = 'port_harcourt_youth'), NOW() - INTERVAL '36 hours'),

  ('Power supply: Darkness everywhere, government dey blame citizens',
   'power-supply-darkness-everywhere-government-dey-blame-citizens',
   'NEPA no dey give light, citizens dey buy fuel for generator. Government dey blame citizens for not paying bills but light no dey come. How person go pay for what he no get? Power must be fixed before 2027!', 
   (SELECT id FROM users WHERE username = 'maiduguri_engineer'), NOW() - INTERVAL '30 hours'),

  ('Agriculture: Farmers dey suffer, food prices dey rise',
   'agriculture-farmers-dey-suffer-food-prices-dey-rise',
   'Fertilizer don become gold, tractors no dey work, roads no dey good. Farmers dey abandon farms. Food import dey rise. How we go feed ourselves? Agriculture must be priority for 2027 candidates!', 
   (SELECT id FROM users WHERE username = 'jos_farmer'), NOW() - INTERVAL '26 hours'),

  ('Religious tension: Christians vs Muslims dey fight over nothing',
   'religious-tension-christians-vs-muslims-dey-fight-over-nothing',
   'Religion don become political tool. Politicians dey use religion to divide us. Christians and Muslims dey fight over politics, not religion. We need to unite as Nigerians, not as religious groups. 2027 election must be about issues, not religion!', 
   (SELECT id FROM users WHERE username = 'sokoto_imam'), NOW() - INTERVAL '20 hours'),

  ('Tribalism: Igbo vs Yoruba vs Hausa dey fight over politics',
   'tribalism-igbo-vs-yoruba-vs-hausa-dey-fight-over-politics',
   'Politicians dey use tribalism to divide us. Igbo dey support Igbo, Yoruba dey support Yoruba, Hausa dey support Hausa. We need to vote for competence, not tribe. 2027 election must break tribal barriers!', 
   (SELECT id FROM users WHERE username = 'benin_artist'), NOW() - INTERVAL '10 hours'),

  ('Foreign policy: Nigeria dey lose respect internationally',
   'foreign-policy-nigeria-dey-lose-respect-internationally',
   'Our passport no dey strong, Nigerians dey deported everywhere. Government no dey protect citizens abroad. International community no dey respect us. We need strong foreign policy. 2027 election must address this!', 
   (SELECT id FROM users WHERE username = 'zaria_professor'), NOW() - INTERVAL '6 hours');

/* COMMENTS - Nigerian Political Discourse (90+ comments) */
INSERT INTO comments (post_id,user_id,content,created_at) VALUES
/* Fuel subsidy thread (8 comments) */
((SELECT id FROM posts WHERE title='Fuel subsidy removal: Na who dey suffer pass?'),
 (SELECT id FROM users WHERE username='warri_oil_worker'),
 'Na poor people dey suffer pass. Rich people dey buy fuel at black market price. Government dey talk about palliatives but we no see anything. 2027 election go hot!', 
 NOW() - INTERVAL '5 days 20 hours'),
((SELECT id FROM posts WHERE title='Fuel subsidy removal: Na who dey suffer pass?'),
 (SELECT id FROM users WHERE username='ilorin_taxi_driver'),
 'My taxi business don suffer. Fuel don reach N700 per liter. How I go make profit? Government no dey think about small business owners. 2027 election, we go show them!', 
 NOW() - INTERVAL '5 days 19 hours'),
((SELECT id FROM posts WHERE title='Fuel subsidy removal: Na who dey suffer pass?'),
 (SELECT id FROM users WHERE username='tinubu_supporter'),
 'Subsidy removal na necessary evil. We no fit continue to subsidize fuel for rich people. Government dey work on palliatives. Give them time!', 
 NOW() - INTERVAL '5 days 18 hours'),
((SELECT id FROM posts WHERE title='Fuel subsidy removal: Na who dey suffer pass?'),
 (SELECT id FROM users WHERE username='peter_obi_fan'),
 'Time for what? People dey die of hunger. Government dey talk about time but citizens dey suffer now. 2027 election, we need better leadership!', 
 NOW() - INTERVAL '5 days 16 hours'),
((SELECT id FROM posts WHERE title='Fuel subsidy removal: Na who dey suffer pass?'),
 (SELECT id FROM users WHERE username='kano_trader'),
 'Market prices don double. Transport fare don double. Everything don double. How poor people go survive? Government no dey care about us!', 
 NOW() - INTERVAL '5 days 12 hours'),
((SELECT id FROM posts WHERE title='Fuel subsidy removal: Na who dey suffer pass?'),
 (SELECT id FROM users WHERE username='abuja_civil_servant'),
 'Even civil servants dey suffer. Salary no dey increase but prices dey increase everyday. Government dey talk about minimum wage but na talk talk!', 
 NOW() - INTERVAL '5 days 10 hours'),
((SELECT id FROM posts WHERE title='Fuel subsidy removal: Na who dey suffer pass?'),
 (SELECT id FROM users WHERE username='bauchi_nurse'),
 'Hospitals no dey get fuel for generators. Patients dey die because of power failure. Government dey talk about healthcare but no dey provide basic needs!', 
 NOW() - INTERVAL '5 days 9 hours'),
((SELECT id FROM posts WHERE title='Fuel subsidy removal: Na who dey suffer pass?'),
 (SELECT id FROM users WHERE username='yola_businesswoman'),
 'Small businesses dey close shop. Big businesses dey survive because they get connections. This country no make sense. 2027 election must bring change!', 
 NOW() - INTERVAL '5 days 7 hours'),

/* Peter Obi 2027 thread (7 comments) */
((SELECT id FROM posts WHERE title='Peter Obi 2027: Can he really win this time?'),
 (SELECT id FROM users WHERE username='atiku_campaign'),
 'Obi movement strong but PDP go give him tough competition. Atiku still have strong base in North. 2027 election go be interesting!', 
 NOW() - INTERVAL '4 days 22 hours'),
((SELECT id FROM posts WHERE title='Peter Obi 2027: Can he really win this time?'),
 (SELECT id FROM users WHERE username='tinubu_supporter'),
 'Obi no fit win. He no get strong party structure. Social media followers no dey vote. Ground work important!', 
 NOW() - INTERVAL '4 days 21 hours'),
((SELECT id FROM posts WHERE title='Peter Obi 2027: Can he really win this time?'),
 (SELECT id FROM users WHERE username='lagos_businessman'),
 'Obi get good ideas but implementation hard. Nigeria need strong leader with experience. 2027 election must be about competence!', 
 NOW() - INTERVAL '4 days 20 hours'),
((SELECT id FROM posts WHERE title='Peter Obi 2027: Can he really win this time?'),
 (SELECT id FROM users WHERE username='enugu_lawyer'),
 'Obi movement dey grow stronger. Young people dey support am. 2027 election, youth vote go decide!', 
 NOW() - INTERVAL '4 days 18 hours'),
((SELECT id FROM posts WHERE title='Peter Obi 2027: Can he really win this time?'),
 (SELECT id FROM users WHERE username='zaria_professor'),
 'Obi need to build strong coalition. One man no fit change Nigeria. He need to work with other parties!', 
 NOW() - INTERVAL '4 days 17 hours'),
((SELECT id FROM posts WHERE title='Peter Obi 2027: Can he really win this time?'),
 (SELECT id FROM users WHERE username='port_harcourt_youth'),
 'Obi movement dey spread like wildfire. Social media dey help am reach more people. 2027 election go be different!', 
 NOW() - INTERVAL '4 days 15 hours'),
((SELECT id FROM posts WHERE title='Peter Obi 2027: Can he really win this time?'),
 (SELECT id FROM users WHERE username='benin_artist'),
 'Obi get good track record as governor. He fit manage resources well. Nigeria need such leader!', 
 NOW() - INTERVAL '4 days 14 hours'),

/* Naira devaluation thread (8 comments) */
((SELECT id FROM posts WHERE title='Naira devaluation: Rich people dey buy dollars, poor people dey suffer'),
 (SELECT id FROM users WHERE username='kano_trader'),
 'Dollar don become gold. Rich people dey buy and keep for future. Poor people dey suffer. This country hard!', 
 NOW() - INTERVAL '4 days'),
((SELECT id FROM posts WHERE title='Naira devaluation: Rich people dey buy dollars, poor people dey suffer'),
 (SELECT id FROM users WHERE username='tinubu_supporter'),
 'Government dey work on stabilizing naira. Floating exchange rate na good policy. Give them time to work!', 
 NOW() - INTERVAL '3 days 23 hours'),
((SELECT id FROM posts WHERE title='Naira devaluation: Rich people dey buy dollars, poor people dey suffer'),
 (SELECT id FROM users WHERE username='lagos_businessman'),
 'Import business don become luxury. Local manufacturers dey close shop. Government need to support local production!', 
 NOW() - INTERVAL '3 days 22 hours'),
((SELECT id FROM posts WHERE title='Naira devaluation: Rich people dey buy dollars, poor people dey suffer'),
 (SELECT id FROM users WHERE username='peter_obi_fan'),
 'Obi talk about this during campaign. He say we need to produce what we consume. Government no dey listen!', 
 NOW() - INTERVAL '3 days 21 hours'),
((SELECT id FROM posts WHERE title='Naira devaluation: Rich people dey buy dollars, poor people dey suffer'),
 (SELECT id FROM users WHERE username='abuja_civil_servant'),
 'Even civil servants dey buy dollars. Salary no dey worth anything. Government need to increase salary!', 
 NOW() - INTERVAL '3 days 19 hours'),
((SELECT id FROM posts WHERE title='Naira devaluation: Rich people dey buy dollars, poor people dey suffer'),
 (SELECT id FROM users WHERE username='warri_oil_worker'),
 'Oil money dey go abroad. Government no dey use oil money to develop Nigeria. We need better management!', 
 NOW() - INTERVAL '3 days 18 hours'),
((SELECT id FROM posts WHERE title='Naira devaluation: Rich people dey buy dollars, poor people dey suffer'),
 (SELECT id FROM users WHERE username='calabar_doctor'),
 'Medical equipment dey become expensive. Hospitals no fit buy new equipment. Healthcare dey suffer!', 
 NOW() - INTERVAL '3 days 17 hours'),
((SELECT id FROM posts WHERE title='Naira devaluation: Rich people dey buy dollars, poor people dey suffer'),
 (SELECT id FROM users WHERE username='jalingo_teacher'),
 'School fees don double. Parents no fit pay. Education dey become luxury. Government need to subsidize education!', 
 NOW() - INTERVAL '3 days 16 hours'),

/* Security situation thread (7 comments) */
((SELECT id FROM posts WHERE title='Security situation: Bandits everywhere, government no dey do anything'),
 (SELECT id FROM users WHERE username='maiduguri_engineer'),
 'Boko Haram still dey operate in Northeast. Government dey talk about defeating them but they still dey kill people!', 
 NOW() - INTERVAL '3 days'),
((SELECT id FROM posts WHERE title='Security situation: Bandits everywhere, government no dey do anything'),
 (SELECT id FROM users WHERE username='tinubu_supporter'),
 'Government dey work on security. Security challenges no dey solve overnight. Give them time!', 
 NOW() - INTERVAL '2 days 23 hours'),
((SELECT id FROM posts WHERE title='Security situation: Bandits everywhere, government no dey do anything'),
 (SELECT id FROM users WHERE username='sokoto_imam'),
 'Bandits dey operate freely. Police and army dey collect salary but no dey work. Citizens dey pay ransom!', 
 NOW() - INTERVAL '2 days 22 hours'),
((SELECT id FROM posts WHERE title='Security situation: Bandits everywhere, government no dey do anything'),
 (SELECT id FROM users WHERE username='peter_obi_fan'),
 'Obi talk about community policing during campaign. Government no dey implement good ideas!', 
 NOW() - INTERVAL '2 days 21 hours'),
((SELECT id FROM posts WHERE title='Security situation: Bandits everywhere, government no dey do anything'),
 (SELECT id FROM users WHERE username='enugu_lawyer'),
 'Even Abuja no safe again. Kidnapping dey happen everywhere. Government dey talk but no dey act!', 
 NOW() - INTERVAL '2 days 19 hours'),
((SELECT id FROM posts WHERE title='Security situation: Bandits everywhere, government no dey do anything'),
 (SELECT id FROM users WHERE username='bauchi_nurse'),
 'Healthcare workers dey afraid to go work. Bandits dey attack hospitals. Government no dey protect us!', 
 NOW() - INTERVAL '2 days 18 hours'),
((SELECT id FROM posts WHERE title='Security situation: Bandits everywhere, government no dey do anything'),
 (SELECT id FROM users WHERE username='yola_businesswoman'),
 'Business no dey move because of insecurity. Investors dey afraid to invest. Economy dey suffer!', 
 NOW() - INTERVAL '2 days 17 hours'),

/* Atiku vs Tinubu thread (6 comments) */
((SELECT id FROM posts WHERE title='Atiku vs Tinubu 2027: Same old story or new chapter?'),
 (SELECT id FROM users WHERE username='peter_obi_fan'),
 'We need young blood. These old men don rule us for too long. 2027 election must bring fresh ideas!', 
 NOW() - INTERVAL '3 days'),
((SELECT id FROM posts WHERE title='Atiku vs Tinubu 2027: Same old story or new chapter?'),
 (SELECT id FROM users WHERE username='tinubu_supporter'),
 'Experience important for leadership. Young people no get experience. We need experienced leaders!', 
 NOW() - INTERVAL '2 days 23 hours'),
((SELECT id FROM posts WHERE title='Atiku vs Tinubu 2027: Same old story or new chapter?'),
 (SELECT id FROM users WHERE username='atiku_campaign'),
 'Atiku get experience and good ideas. He fit manage Nigeria economy well. 2027 election, experience go count!', 
 NOW() - INTERVAL '2 days 22 hours'),
((SELECT id FROM posts WHERE title='Atiku vs Tinubu 2027: Same old story or new chapter?'),
 (SELECT id FROM users WHERE username='port_harcourt_youth'),
 'Young people need to wake up and take over. These old men dey recycle themselves. 2027 must be different!', 
 NOW() - INTERVAL '2 days 21 hours'),
((SELECT id FROM posts WHERE title='Atiku vs Tinubu 2027: Same old story or new chapter?'),
 (SELECT id FROM users WHERE username='zaria_professor'),
 'We need leaders with vision, not just experience. Young people get fresh ideas. 2027 election must be about vision!', 
 NOW() - INTERVAL '2 days 19 hours'),
((SELECT id FROM posts WHERE title='Atiku vs Tinubu 2027: Same old story or new chapter?'),
 (SELECT id FROM users WHERE username='benin_artist'),
 'Artists and creatives dey support young leaders. We need change in 2027. No more recycled politicians!', 
 NOW() - INTERVAL '2 days 18 hours'),

/* Minimum wage thread (6 comments) */
((SELECT id FROM posts WHERE title='Minimum wage: N30,000 no fit buy anything again'),
 (SELECT id FROM users WHERE username='abuja_civil_servant'),
 'Civil servants dey suffer. Salary no dey increase but prices dey increase everyday. Government dey talk about new minimum wage but na talk talk!', 
 NOW() - INTERVAL '2 days'),
((SELECT id FROM posts WHERE title='Minimum wage: N30,000 no fit buy anything again'),
 (SELECT id FROM users WHERE username='bauchi_nurse'),
 'Healthcare workers dey work hard but salary no dey worth anything. Government need to increase salary!', 
 NOW() - INTERVAL '1 days 23 hours'),
((SELECT id FROM posts WHERE title='Minimum wage: N30,000 no fit buy anything again'),
 (SELECT id FROM users WHERE username='jalingo_teacher'),
 'Teachers dey work hard but salary no dey worth anything. Education dey suffer because of poor salary!', 
 NOW() - INTERVAL '1 days 22 hours'),
((SELECT id FROM posts WHERE title='Minimum wage: N30,000 no fit buy anything again'),
 (SELECT id FROM users WHERE username='tinubu_supporter'),
 'Government dey work on new minimum wage. Give them time to negotiate with labor unions!', 
 NOW() - INTERVAL '1 days 21 hours'),
((SELECT id FROM posts WHERE title='Minimum wage: N30,000 no fit buy anything again'),
 (SELECT id FROM users WHERE username='peter_obi_fan'),
 'Obi talk about living wage during campaign. Government no dey implement good ideas!', 
 NOW() - INTERVAL '1 days 19 hours'),
((SELECT id FROM posts WHERE title='Minimum wage: N30,000 no fit buy anything again'),
 (SELECT id FROM users WHERE username='warri_oil_worker'),
 'Oil workers dey get good salary but other workers dey suffer. We need fair distribution of wealth!', 
 NOW() - INTERVAL '1 days 18 hours'),

/* Education crisis thread (5 comments) */
((SELECT id FROM posts WHERE title='Education crisis: Our children no dey learn anything'),
 (SELECT id FROM users WHERE username='ibadan_student'),
 'ASUU strike dey affect our education. Government no dey care about students. 2027 election, education must be priority!', 
 NOW() - INTERVAL '2 days'),
((SELECT id FROM posts WHERE title='Education crisis: Our children no dey learn anything'),
 (SELECT id FROM users WHERE username='jalingo_teacher'),
 'Teachers dey work hard but facilities no dey good. Government need to invest in education!', 
 NOW() - INTERVAL '1 days 23 hours'),
((SELECT id FROM posts WHERE title='Education crisis: Our children no dey learn anything'),
 (SELECT id FROM users WHERE username='zaria_professor'),
 'University education dey become luxury. Poor people no fit send their children to university!', 
 NOW() - INTERVAL '1 days 22 hours'),
((SELECT id FROM posts WHERE title='Education crisis: Our children no dey learn anything'),
 (SELECT id FROM users WHERE username='peter_obi_fan'),
 'Obi talk about education reform during campaign. Government no dey implement good ideas!', 
 NOW() - INTERVAL '1 days 21 hours'),
((SELECT id FROM posts WHERE title='Education crisis: Our children no dey learn anything'),
 (SELECT id FROM users WHERE username='tinubu_supporter'),
 'Government dey work on education reform. Give them time to implement changes!', 
 NOW() - INTERVAL '1 days 19 hours'),

/* Healthcare system thread (5 comments) */
((SELECT id FROM posts WHERE title='Healthcare system: Hospitals dey kill people more than sickness'),
 (SELECT id FROM users WHERE username='calabar_doctor'),
 'Government hospitals no dey work. Private hospitals dey charge like international rates. Poor people dey die because they no get money for treatment!', 
 NOW() - INTERVAL '1 days'),
((SELECT id FROM posts WHERE title='Healthcare system: Hospitals dey kill people more than sickness'),
 (SELECT id FROM users WHERE username='bauchi_nurse'),
 'Nurses dey work hard but salary no dey worth anything. Government need to increase healthcare workers salary!', 
 NOW() - INTERVAL '23 hours'),
((SELECT id FROM posts WHERE title='Healthcare system: Hospitals dey kill people more than sickness'),
 (SELECT id FROM users WHERE username='peter_obi_fan'),
 'Obi talk about healthcare reform during campaign. Government no dey implement good ideas!', 
 NOW() - INTERVAL '22 hours'),
((SELECT id FROM posts WHERE title='Healthcare system: Hospitals dey kill people more than sickness'),
 (SELECT id FROM users WHERE username='tinubu_supporter'),
 'Government dey work on healthcare reform. Give them time to implement changes!', 
 NOW() - INTERVAL '21 hours'),
((SELECT id FROM posts WHERE title='Healthcare system: Hospitals dey kill people more than sickness'),
 (SELECT id FROM users WHERE username='enugu_lawyer'),
 'Health insurance no dey work. Poor people no fit afford healthcare. Government need to provide free healthcare!', 
 NOW() - INTERVAL '20 hours'),

/* Corruption thread (5 comments) */
((SELECT id FROM posts WHERE title='Corruption: EFCC dey catch small thieves, big thieves dey rule'),
 (SELECT id FROM users WHERE username='enugu_lawyer'),
 'Politicians dey steal billions, EFCC dey catch Yahoo boys. Big thieves dey walk free, small thieves dey go jail. This country no make sense!', 
 NOW() - INTERVAL '1 days'),
((SELECT id FROM posts WHERE title='Corruption: EFCC dey catch small thieves, big thieves dey rule'),
 (SELECT id FROM users WHERE username='peter_obi_fan'),
 'Obi talk about fighting corruption during campaign. Government no dey implement good ideas!', 
 NOW() - INTERVAL '23 hours'),
((SELECT id FROM posts WHERE title='Corruption: EFCC dey catch small thieves, big thieves dey rule'),
 (SELECT id FROM users WHERE username='tinubu_supporter'),
 'Government dey fight corruption. EFCC dey work hard. Give them time to catch all thieves!', 
 NOW() - INTERVAL '22 hours'),
((SELECT id FROM posts WHERE title='Corruption: EFCC dey catch small thieves, big thieves dey rule'),
 (SELECT id FROM users WHERE username='zaria_professor'),
 'Corruption dey kill our country. We need leaders with integrity. 2027 election must be about integrity!', 
 NOW() - INTERVAL '21 hours'),
((SELECT id FROM posts WHERE title='Corruption: EFCC dey catch small thieves, big thieves dey rule'),
 (SELECT id FROM users WHERE username='benin_artist'),
 'Artists dey suffer because of corruption. Government no dey support arts and culture!', 
 NOW() - INTERVAL '20 hours'),

/* Youth unemployment thread (5 comments) */
((SELECT id FROM posts WHERE title='Youth unemployment: 50% of graduates no get job'),
 (SELECT id FROM users WHERE username='port_harcourt_youth'),
 'NYSC dey pay N33,000, graduates dey do okada. Government dey talk about job creation but na talk talk. Young people dey leave Nigeria in droves!', 
 NOW() - INTERVAL '1 days'),
((SELECT id FROM posts WHERE username='peter_obi_fan'),
 'Obi talk about job creation during campaign. Government no dey implement good ideas!', 
 NOW() - INTERVAL '23 hours'),
((SELECT id FROM posts WHERE title='Youth unemployment: 50% of graduates no get job'),
 (SELECT id FROM users WHERE username='tinubu_supporter'),
 'Government dey work on job creation. Give them time to create more jobs!', 
 NOW() - INTERVAL '22 hours'),
((SELECT id FROM posts WHERE title='Youth unemployment: 50% of graduates no get job'),
 (SELECT id FROM users WHERE username='lagos_businessman'),
 'Private sector need to create more jobs. Government need to support private sector!', 
 NOW() - INTERVAL '21 hours'),
((SELECT id FROM posts WHERE title='Youth unemployment: 50% of graduates no get job'),
 (SELECT id FROM users WHERE username='warri_oil_worker'),
 'Oil sector dey employ few people. We need to diversify economy. Government need to support other sectors!', 
 NOW() - INTERVAL '20 hours'),

/* Power supply thread (4 comments) */
((SELECT id FROM posts WHERE title='Power supply: Darkness everywhere, government dey blame citizens'),
 (SELECT id FROM users WHERE username='maiduguri_engineer'),
 'NEPA no dey give light, citizens dey buy fuel for generator. Government dey blame citizens for not paying bills but light no dey come!', 
 NOW() - INTERVAL '1 days'),
((SELECT id FROM posts WHERE title='Power supply: Darkness everywhere, government dey blame citizens'),
 (SELECT id FROM users WHERE username='peter_obi_fan'),
 'Obi talk about power reform during campaign. Government no dey implement good ideas!', 
 NOW() - INTERVAL '23 hours'),
((SELECT id FROM posts WHERE title='Power supply: Darkness everywhere, government dey blame citizens'),
 (SELECT id FROM users WHERE username='tinubu_supporter'),
 'Government dey work on power reform. Give them time to fix power problem!', 
 NOW() - INTERVAL '22 hours'),
((SELECT id FROM posts WHERE title='Power supply: Darkness everywhere, government dey blame citizens'),
 (SELECT id FROM users WHERE username='lagos_businessman'),
 'Businesses dey suffer because of power problem. Government need to fix power before 2027!', 
 NOW() - INTERVAL '21 hours'),

/* Agriculture thread (4 comments) */
((SELECT id FROM posts WHERE title='Agriculture: Farmers dey suffer, food prices dey rise'),
 (SELECT id FROM users WHERE username='jos_farmer'),
 'Fertilizer don become gold, tractors no dey work, roads no dey good. Farmers dey abandon farms. Food import dey rise!', 
 NOW() - INTERVAL '1 days'),
((SELECT id FROM posts WHERE title='Agriculture: Farmers dey suffer, food prices dey rise'),
 (SELECT id FROM users WHERE username='peter_obi_fan'),
 'Obi talk about agricultural reform during campaign. Government no dey implement good ideas!', 
 NOW() - INTERVAL '23 hours'),
((SELECT id FROM posts WHERE title='Agriculture: Farmers dey suffer, food prices dey rise'),
 (SELECT id FROM users WHERE username='tinubu_supporter'),
 'Government dey work on agricultural reform. Give them time to support farmers!', 
 NOW() - INTERVAL '22 hours'),
((SELECT id FROM posts WHERE title='Agriculture: Farmers dey suffer, food prices dey rise'),
 (SELECT id FROM users WHERE username='kano_trader'),
 'Food prices dey rise because of poor agricultural policy. Government need to support farmers!', 
 NOW() - INTERVAL '21 hours'),

/* Religious tension thread (3 comments) */
((SELECT id FROM posts WHERE title='Religious tension: Christians vs Muslims dey fight over nothing'),
 (SELECT id FROM users WHERE username='sokoto_imam'),
 'Religion don become political tool. Politicians dey use religion to divide us. Christians and Muslims dey fight over politics, not religion!', 
 NOW() - INTERVAL '1 days'),
((SELECT id FROM posts WHERE title='Religious tension: Christians vs Muslims dey fight over nothing'),
 (SELECT id FROM users WHERE username='peter_obi_fan'),
 'Obi talk about unity during campaign. Government no dey implement good ideas!', 
 NOW() - INTERVAL '23 hours'),
((SELECT id FROM posts WHERE title='Religious tension: Christians vs Muslims dey fight over nothing'),
 (SELECT id FROM users WHERE username='tinubu_supporter'),
 'Government dey work on unity. Give them time to unite Nigerians!', 
 NOW() - INTERVAL '22 hours'),

/* Tribalism thread (3 comments) */
((SELECT id FROM posts WHERE title='Tribalism: Igbo vs Yoruba vs Hausa dey fight over politics'),
 (SELECT id FROM users WHERE username='benin_artist'),
 'Politicians dey use tribalism to divide us. Igbo dey support Igbo, Yoruba dey support Yoruba, Hausa dey support Hausa. We need to vote for competence!', 
 NOW() - INTERVAL '1 days'),
((SELECT id FROM posts WHERE title='Tribalism: Igbo vs Yoruba vs Hausa dey fight over politics'),
 (SELECT id FROM users WHERE username='peter_obi_fan'),
 'Obi talk about unity during campaign. Government no dey implement good ideas!', 
 NOW() - INTERVAL '23 hours'),
((SELECT id FROM posts WHERE title='Tribalism: Igbo vs Yoruba vs Hausa dey fight over politics'),
 (SELECT id FROM users WHERE username='tinubu_supporter'),
 'Government dey work on unity. Give them time to unite Nigerians!', 
 NOW() - INTERVAL '22 hours'),

/* Foreign policy thread (3 comments) */
((SELECT id FROM posts WHERE title='Foreign policy: Nigeria dey lose respect internationally'),
 (SELECT id FROM users WHERE username='zaria_professor'),
 'Our passport no dey strong, Nigerians dey deported everywhere. Government no dey protect citizens abroad. International community no dey respect us!', 
 NOW() - INTERVAL '1 days'),
((SELECT id FROM posts WHERE title='Foreign policy: Nigeria dey lose respect internationally'),
 (SELECT id FROM users WHERE username='peter_obi_fan'),
 'Obi talk about foreign policy reform during campaign. Government no dey implement good ideas!', 
 NOW() - INTERVAL '23 hours'),
((SELECT id FROM posts WHERE title='Foreign policy: Nigeria dey lose respect internationally'),
 (SELECT id FROM users WHERE username='tinubu_supporter'),
 'Government dey work on foreign policy. Give them time to improve international relations!', 
 NOW() - INTERVAL '22 hours');

/* OPTIONAL: auto-generate lightweight votes 
   (one up- or down-vote per user-post pair, random-ish)      */
INSERT INTO post_votes (post_id,user_id,vote_type)
SELECT p.id, u.id,
       CASE WHEN RANDOM() < 0.75 THEN 'upvote' ELSE 'downvote' END
FROM posts p
JOIN users u ON u.id % 7 = p.id % 7;   -- simple scatter pattern
