/* mega_seed.sql ────────────────────────────────────────────
   DEMO PLATFORM - Generic Discussion Forum
   LeftPlot.site - Public Demo Version
------------------------------------------------------------*/

/* ADD USERS - Demo Users */
INSERT INTO users (username,email,password,role,created_at,verified) VALUES
  ('tech_enthusiast'    ,'tech_fan@demo.com'       ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('web_developer'       ,'web_dev@demo.com'          ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('data_scientist'      ,'data_sci@demo.com'       ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('startup_founder'   ,'startup@demo.com'        ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('student_coder'      ,'student@demo.com'     ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('senior_engineer' ,'senior@demo.com'          ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('ui_designer'         ,'designer@demo.com'       ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('product_manager'        ,'pm@demo.com'        ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('devops_engineer' ,'devops@demo.com'         ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('mobile_developer'      ,'mobile@demo.com'    ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('security_expert'      ,'security@demo.com'       ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('ai_researcher'  ,'ai_research@demo.com'    ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('frontend_dev'          ,'frontend@demo.com'          ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('backend_dev'         ,'backend@demo.com'      ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('qa_engineer'        ,'qa@demo.com'         ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('system_admin'     ,'sysadmin@demo.com'        ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('cloud_architect'    ,'cloud@demo.com'         ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('database_admin'        ,'dba@demo.com'      ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('network_engineer'  ,'network@demo.com'       ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('fullstack_dev'     ,'fullstack@demo.com'     ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true),
  ('tech_lead'  ,'techlead@demo.com'          ,'$2b$10$Zb9GxgVlQ7h4ZC7v0UTH0u2tY9K4HE0POrrjhWTX5cvQDPHxjkilm','user',NOW(),true);

/* 15 DEMO POSTS - Technology Discussion Focus */
INSERT INTO posts (title,slug,content,user_id,created_at) VALUES
  ('What''s the best framework for building modern web applications?',
   'best-framework-modern-web-applications',
   'I''m starting a new project and need to choose between React, Vue, Angular, and Svelte. Each has its pros and cons. React has the largest ecosystem, Vue is easier to learn, Angular is enterprise-ready, and Svelte is the newest with great performance. What are your experiences with these frameworks?', 
   (SELECT id FROM users WHERE username = 'web_developer'), NOW() - INTERVAL '6 days'),

  ('Microservices vs Monolith: Which architecture should I choose?',
   'microservices-vs-monolith-architecture-choice',
   'My team is debating whether to go with microservices or a monolithic architecture for our new application. Microservices offer scalability and flexibility but add complexity. Monoliths are simpler to develop but harder to scale. What factors should we consider in making this decision?',  
   (SELECT id FROM users WHERE username = 'senior_engineer'), NOW() - INTERVAL '5 days'),

  ('The future of AI in software development',
   'future-ai-software-development',
   'With tools like GitHub Copilot and ChatGPT becoming more prevalent, how do you think AI will change the software development landscape? Will it replace developers or augment their capabilities? What skills should we focus on to stay relevant?',  
   (SELECT id FROM users WHERE username = 'ai_researcher'), NOW() - INTERVAL '5 days 3 hours'),

  ('Best practices for securing web applications',
   'best-practices-securing-web-applications',
   'Security is becoming increasingly important. What are the most critical security practices that every developer should implement? From input validation to authentication, what are your go-to security measures?', 
   (SELECT id FROM users WHERE username = 'security_expert'), NOW() - INTERVAL '4 days'),

  ('Docker vs Kubernetes: When to use each?',
   'docker-vs-kubernetes-when-use-each',
   'I understand Docker for containerization, but when should I consider Kubernetes? For small projects, Docker Compose might be sufficient, but Kubernetes offers orchestration at scale. What are the tipping points for choosing one over the other?', 
   (SELECT id FROM users WHERE username = 'devops_engineer'), NOW() - INTERVAL '4 days'),

  ('The rise of TypeScript: Is it worth learning?',
   'rise-typescript-worth-learning',
   'TypeScript seems to be everywhere now. Many companies are migrating from JavaScript to TypeScript. What are the real benefits? Does it actually improve code quality and developer experience, or is it just another layer of complexity?', 
   (SELECT id FROM users WHERE username = 'frontend_dev'), NOW() - INTERVAL '3 days'),

  ('Database design patterns for scalable applications',
   'database-design-patterns-scalable-applications',
   'As applications grow, database design becomes crucial. What patterns and strategies do you use for designing databases that can handle high loads? From indexing strategies to data partitioning, what are your best practices?', 
   (SELECT id FROM users WHERE username = 'database_admin'), NOW() - INTERVAL '3 days'),

  ('Cloud computing: AWS vs Azure vs Google Cloud',
   'cloud-computing-aws-azure-google-cloud',
   'Which cloud provider do you prefer and why? AWS has the largest market share, Azure integrates well with Microsoft products, and Google Cloud has strong AI/ML capabilities. What factors should influence the choice?', 
   (SELECT id FROM users WHERE username = 'cloud_architect'), NOW() - INTERVAL '2 days'),

  ('Testing strategies for modern applications',
   'testing-strategies-modern-applications',
   'With the complexity of modern applications, testing has become more important than ever. What testing strategies do you use? Unit tests, integration tests, E2E tests - how do you balance coverage with development speed?', 
   (SELECT id FROM users WHERE username = 'qa_engineer'), NOW() - INTERVAL '2 days'),

  ('The impact of remote work on software development',
   'impact-remote-work-software-development',
   'Remote work has become the norm for many development teams. How has this changed your development process? What tools and practices have you adopted to maintain productivity and collaboration in a remote environment?', 
   (SELECT id FROM users WHERE username = 'tech_lead'), NOW() - INTERVAL '36 hours'),

  ('Performance optimization techniques for web apps',
   'performance-optimization-techniques-web-apps',
   'User experience is heavily influenced by performance. What techniques do you use to optimize web application performance? From code splitting to lazy loading, what are the most effective strategies you''ve implemented?', 
   (SELECT id FROM users WHERE username = 'fullstack_dev'), NOW() - INTERVAL '30 hours'),

  ('The future of mobile app development',
   'future-mobile-app-development',
   'With React Native, Flutter, and native development options available, what do you think the future holds for mobile app development? Will cross-platform solutions dominate, or will native development remain the gold standard?', 
   (SELECT id FROM users WHERE username = 'mobile_developer'), NOW() - INTERVAL '26 hours'),

  ('API design best practices',
   'api-design-best-practices',
   'Designing good APIs is crucial for developer experience. What are your best practices for API design? REST vs GraphQL, versioning strategies, error handling - what principles do you follow?', 
   (SELECT id FROM users WHERE username = 'backend_dev'), NOW() - INTERVAL '20 hours'),

  ('The role of design systems in modern development',
   'role-design-systems-modern-development',
   'Design systems like Material Design and Ant Design are becoming standard. How do you approach design systems in your projects? Do you build custom ones or use existing frameworks? What are the trade-offs?', 
   (SELECT id FROM users WHERE username = 'ui_designer'), NOW() - INTERVAL '10 hours'),

  ('Career advice for junior developers',
   'career-advice-junior-developers',
   'For those just starting their development careers, what advice would you give? What skills should they focus on, what mistakes should they avoid, and how can they accelerate their growth in the industry?', 
   (SELECT id FROM users WHERE username = 'student_coder'), NOW() - INTERVAL '6 hours');

/* COMMENTS - Technology Discussion (90+ comments) */
INSERT INTO comments (post_id,user_id,content,created_at) VALUES
/* Framework discussion thread (8 comments) */
((SELECT id FROM posts WHERE title='What''s the best framework for building modern web applications?'),
 (SELECT id FROM users WHERE username='frontend_dev'),
 'React has the largest ecosystem and community support. The learning curve is steep but worth it for the job opportunities. Vue is great for smaller projects and teams new to frontend frameworks.', 
 NOW() - INTERVAL '5 days 20 hours'),
((SELECT id FROM posts WHERE title='What''s the best framework for building modern web applications?'),
 (SELECT id FROM users WHERE username='senior_engineer'),
 'I''ve used all four extensively. React is the safest choice for career growth, Vue is the most pleasant to work with, Angular is overkill for most projects, and Svelte is exciting but still maturing.', 
 NOW() - INTERVAL '5 days 19 hours'),
((SELECT id FROM posts WHERE title='What''s the best framework for building modern web applications?'),
 (SELECT id FROM users WHERE username='tech_enthusiast'),
 'Don''t forget about the build tools! Vite with Vue or Svelte provides amazing development experience. The framework choice often depends on your team''s experience and project requirements.', 
 NOW() - INTERVAL '5 days 18 hours'),
((SELECT id FROM posts WHERE title='What''s the best framework for building modern web applications?'),
 (SELECT id FROM users WHERE username='product_manager'),
 'Consider the business perspective too. React has the most developers available for hiring, which can be crucial for scaling teams. Framework choice isn''t just about technical merits.', 
 NOW() - INTERVAL '5 days 16 hours'),
((SELECT id FROM posts WHERE title='What''s the best framework for building modern web applications?'),
 (SELECT id FROM users WHERE username='startup_founder'),
 'For startups, I''d recommend Vue or React. Vue is easier to get started with, while React has better long-term scalability. The ecosystem matters more than the framework itself.', 
 NOW() - INTERVAL '5 days 12 hours'),
((SELECT id FROM posts WHERE title='What''s the best framework for building modern web applications?'),
 (SELECT id FROM users WHERE username='data_scientist'),
 'As someone who works with data visualization, React has the best libraries (D3.js integration, Chart.js wrappers). The ecosystem for data-heavy applications is unmatched.', 
 NOW() - INTERVAL '5 days 10 hours'),
((SELECT id FROM posts WHERE title='What''s the best framework for building modern web applications?'),
 (SELECT id FROM users WHERE username='ui_designer'),
 'From a design perspective, Vue''s single-file components make it easier to maintain design consistency. The template syntax is more intuitive for designers working with developers.', 
 NOW() - INTERVAL '5 days 9 hours'),
((SELECT id FROM posts WHERE title='What''s the best framework for building modern web applications?'),
 (SELECT id FROM users WHERE username='fullstack_dev'),
 'I''ve built the same app in React, Vue, and Svelte. Svelte was the fastest to develop and had the best performance, but the ecosystem is still growing. React is the safe choice for production.', 
 NOW() - INTERVAL '5 days 7 hours'),

/* Microservices vs Monolith thread (7 comments) */
((SELECT id FROM posts WHERE title='Microservices vs Monolith: Which architecture should I choose?'),
 (SELECT id FROM users WHERE username='senior_engineer'),
 'Start with a monolith. You can always break it down later. Microservices add complexity that you don''t need until you have scale problems. Premature optimization is the root of all evil.', 
 NOW() - INTERVAL '4 days 22 hours'),
((SELECT id FROM posts WHERE title='Microservices vs Monolith: Which architecture should I choose?'),
 (SELECT id FROM users WHERE username='devops_engineer'),
 'Microservices require significant DevOps investment. You need proper monitoring, logging, and deployment pipelines. If you don''t have these, stick with a monolith.', 
 NOW() - INTERVAL '4 days 21 hours'),
((SELECT id FROM posts WHERE title='Microservices vs Monolith: Which architecture should I choose?'),
 (SELECT id FROM users WHERE username='tech_lead'),
 'The decision should be based on team size and organizational structure. If you have multiple teams working on different parts, microservices can help with autonomy.', 
 NOW() - INTERVAL '4 days 20 hours'),
((SELECT id FROM posts WHERE username='cloud_architect'),
 'Cloud providers make microservices easier to manage. AWS Lambda, Azure Functions, and Google Cloud Run reduce the operational overhead significantly.', 
 NOW() - INTERVAL '4 days 18 hours'),
((SELECT id FROM posts WHERE title='Microservices vs Monolith: Which architecture should I choose?'),
 (SELECT id FROM users WHERE username='database_admin'),
 'Database design becomes much more complex with microservices. You need to think about data consistency, transactions, and eventual consistency patterns.', 
 NOW() - INTERVAL '4 days 17 hours'),
((SELECT id FROM posts WHERE title='Microservices vs Monolith: Which architecture should I choose?'),
 (SELECT id FROM users WHERE username='startup_founder'),
 'For startups, monoliths are faster to build and deploy. Focus on getting your product right before worrying about scaling architecture.', 
 NOW() - INTERVAL '4 days 15 hours'),
((SELECT id FROM posts WHERE title='Microservices vs Monolith: Which architecture should I choose?'),
 (SELECT id FROM users WHERE username='security_expert'),
 'Security is more complex with microservices. You need to secure service-to-service communication, implement proper authentication across services, and manage secrets.', 
 NOW() - INTERVAL '4 days 14 hours'),

/* AI in software development thread (8 comments) */
((SELECT id FROM posts WHERE title='The future of AI in software development'),
 (SELECT id FROM users WHERE username='ai_researcher'),
 'AI will augment developers, not replace them. Tools like GitHub Copilot are already improving productivity by 20-30%. The key is learning to work effectively with AI assistants.', 
 NOW() - INTERVAL '4 days'),
((SELECT id FROM posts WHERE title='The future of AI in software development'),
 (SELECT id FROM users WHERE username='web_developer'),
 'I use ChatGPT daily for code reviews and debugging. It''s like having a senior developer available 24/7. The quality of suggestions has improved dramatically over the past year.', 
 NOW() - INTERVAL '3 days 23 hours'),
((SELECT id FROM posts WHERE title='The future of AI in software development'),
 (SELECT id FROM users WHERE username='tech_lead'),
 'AI is changing how we interview developers. We need to focus on problem-solving skills rather than memorizing syntax. AI can handle the boilerplate code.', 
 NOW() - INTERVAL '3 days 22 hours'),
((SELECT id FROM posts WHERE title='The future of AI in software development'),
 (SELECT id FROM users WHERE username='student_coder'),
 'As a student, AI tools help me learn faster. I can ask questions and get explanations that help me understand concepts better than just reading documentation.', 
 NOW() - INTERVAL '3 days 21 hours'),
((SELECT id FROM posts WHERE title='The future of AI in software development'),
 (SELECT id FROM users WHERE username='product_manager'),
 'AI is helping with requirements gathering and user story creation. It can analyze user feedback and suggest improvements to product features.', 
 NOW() - INTERVAL '3 days 19 hours'),
((SELECT id FROM posts WHERE title='The future of AI in software development'),
 (SELECT id FROM users WHERE username='qa_engineer'),
 'AI is revolutionizing testing. Automated test generation, visual regression testing, and intelligent bug detection are becoming standard practices.', 
 NOW() - INTERVAL '3 days 18 hours'),
((SELECT id FROM posts WHERE title='The future of AI in software development'),
 (SELECT id FROM users WHERE username='security_expert'),
 'AI is also being used for security testing and vulnerability detection. However, we need to be careful about AI-generated code that might introduce security flaws.', 
 NOW() - INTERVAL '3 days 17 hours'),
((SELECT id FROM posts WHERE title='The future of AI in software development'),
 (SELECT id FROM users WHERE username='data_scientist'),
 'The integration of AI into development workflows is creating new roles. We need developers who understand both traditional programming and AI/ML concepts.', 
 NOW() - INTERVAL '3 days 16 hours'),

/* Security practices thread (7 comments) */
((SELECT id FROM posts WHERE title='Best practices for securing web applications'),
 (SELECT id FROM users WHERE username='security_expert'),
 'Start with OWASP Top 10. Input validation, proper authentication, secure communication (HTTPS), and regular security audits are essential. Don''t forget about dependency scanning.', 
 NOW() - INTERVAL '3 days'),
((SELECT id FROM posts WHERE title='Best practices for securing web applications'),
 (SELECT id FROM users WHERE username='backend_dev'),
 'Use parameterized queries to prevent SQL injection. Implement proper session management and use secure cookies. Always validate and sanitize user input.', 
 NOW() - INTERVAL '2 days 23 hours'),
((SELECT id FROM posts WHERE title='Best practices for securing web applications'),
 (SELECT id FROM users WHERE username='frontend_dev'),
 'Implement Content Security Policy (CSP) headers. Use HTTPS everywhere and avoid storing sensitive data in localStorage. Consider using security headers like HSTS.', 
 NOW() - INTERVAL '2 days 22 hours'),
((SELECT id FROM posts WHERE title='Best practices for securing web applications'),
 (SELECT id FROM users WHERE username='devops_engineer'),
 'Automate security scanning in your CI/CD pipeline. Use tools like SonarQube, Snyk, and OWASP ZAP. Regular penetration testing is crucial.', 
 NOW() - INTERVAL '2 days 21 hours'),
((SELECT id FROM posts WHERE title='Best practices for securing web applications'),
 (SELECT id FROM users WHERE username='database_admin'),
 'Database security is often overlooked. Use least privilege principle, encrypt sensitive data at rest, and implement proper backup and recovery procedures.', 
 NOW() - INTERVAL '2 days 19 hours'),
((SELECT id FROM posts WHERE title='Best practices for securing web applications'),
 (SELECT id FROM users WHERE username='cloud_architect'),
 'Cloud security is different from traditional security. Use IAM properly, implement network security groups, and leverage cloud-native security services.', 
 NOW() - INTERVAL '2 days 18 hours'),
((SELECT id FROM posts WHERE title='Best practices for securing web applications'),
 (SELECT id FROM users WHERE username='tech_lead'),
 'Security should be everyone''s responsibility, not just the security team. Include security requirements in your definition of done and train your team regularly.', 
 NOW() - INTERVAL '2 days 17 hours'),

/* Docker vs Kubernetes thread (6 comments) */
((SELECT id FROM posts WHERE title='Docker vs Kubernetes: When to use each?'),
 (SELECT id FROM users WHERE username='devops_engineer'),
 'Start with Docker Compose for development and small deployments. Kubernetes is overkill unless you have multiple services that need orchestration and scaling.', 
 NOW() - INTERVAL '3 days'),
((SELECT id FROM posts WHERE title='Docker vs Kubernetes: When to use each?'),
 (SELECT id FROM users WHERE username='cloud_architect'),
 'Managed Kubernetes services (EKS, AKS, GKE) reduce the operational overhead significantly. If you''re already in the cloud, Kubernetes becomes more attractive.', 
 NOW() - INTERVAL '2 days 23 hours'),
((SELECT id FROM posts WHERE title='Docker vs Kubernetes: When to use each?'),
 (SELECT id FROM users WHERE username='senior_engineer'),
 'The learning curve for Kubernetes is steep. Make sure your team has the skills and time to invest in learning it. Docker Swarm might be a good middle ground.', 
 NOW() - INTERVAL '2 days 22 hours'),
((SELECT id FROM posts WHERE title='Docker vs Kubernetes: When to use each?'),
 (SELECT id FROM users WHERE username='startup_founder'),
 'For startups, focus on getting your product right first. Docker is sufficient for most early-stage companies. Kubernetes can be added later when you have scale.', 
 NOW() - INTERVAL '2 days 21 hours'),
((SELECT id FROM posts WHERE title='Docker vs Kubernetes: When to use each?'),
 (SELECT id FROM users WHERE username='system_admin'),
 'Kubernetes requires significant infrastructure knowledge. You need to understand networking, storage, and cluster management. Don''t underestimate the operational complexity.', 
 NOW() - INTERVAL '2 days 19 hours'),
((SELECT id FROM posts WHERE title='Docker vs Kubernetes: When to use each?'),
 (SELECT id FROM users WHERE username='tech_lead'),
 'Consider your team size and expertise. Kubernetes requires dedicated DevOps resources. If you don''t have that, stick with simpler container orchestration solutions.', 
 NOW() - INTERVAL '2 days 18 hours'),

/* TypeScript discussion thread (6 comments) */
((SELECT id FROM posts WHERE title='The rise of TypeScript: Is it worth learning?'),
 (SELECT id FROM users WHERE username='frontend_dev'),
 'TypeScript has saved me countless hours of debugging. The type safety catches errors at compile time that would otherwise cause runtime issues. Definitely worth learning.', 
 NOW() - INTERVAL '2 days'),
((SELECT id FROM posts WHERE title='The rise of TypeScript: Is it worth learning?'),
 (SELECT id FROM users WHERE username='senior_engineer'),
 'TypeScript improves code maintainability and developer experience. The IDE support is excellent, and refactoring becomes much safer. It''s becoming the standard for large projects.', 
 NOW() - INTERVAL '1 days 23 hours'),
((SELECT id FROM posts WHERE title='The rise of TypeScript: Is it worth learning?'),
 (SELECT id FROM users WHERE username='student_coder'),
 'As a beginner, TypeScript helped me understand JavaScript better. The type annotations serve as documentation and make the code more readable.', 
 NOW() - INTERVAL '1 days 22 hours'),
((SELECT id FROM posts WHERE title='The rise of TypeScript: Is it worth learning?'),
 (SELECT id FROM users WHERE username='product_manager'),
 'From a business perspective, TypeScript reduces bugs and improves development velocity. The initial learning curve is worth the long-term benefits.', 
 NOW() - INTERVAL '1 days 21 hours'),
((SELECT id FROM posts WHERE title='The rise of TypeScript: Is it worth learning?'),
 (SELECT id FROM users WHERE username='backend_dev'),
 'TypeScript is especially valuable for full-stack development. Having consistent types across frontend and backend improves API design and reduces integration issues.', 
 NOW() - INTERVAL '1 days 19 hours'),
((SELECT id FROM posts WHERE title='The rise of TypeScript: Is it worth learning?'),
 (SELECT id FROM users WHERE username='tech_lead'),
 'TypeScript is becoming a requirement for many job postings. Learning it now will make you more marketable and prepare you for modern development practices.', 
 NOW() - INTERVAL '1 days 18 hours'),

/* Database design thread (5 comments) */
((SELECT id FROM posts WHERE title='Database design patterns for scalable applications'),
 (SELECT id FROM users WHERE username='database_admin'),
 'Start with proper normalization, but don''t over-normalize. Denormalization is often necessary for performance. Use indexes strategically and monitor query performance.', 
 NOW() - INTERVAL '2 days'),
((SELECT id FROM posts WHERE title='Database design patterns for scalable applications'),
 (SELECT id FROM users WHERE username='senior_engineer'),
 'Consider read vs write patterns. For read-heavy applications, consider read replicas and caching. For write-heavy applications, think about sharding strategies.', 
 NOW() - INTERVAL '1 days 23 hours'),
((SELECT id FROM posts WHERE title='Database design patterns for scalable applications'),
 (SELECT id FROM users WHERE username='cloud_architect'),
 'Cloud databases offer built-in scaling features. Use managed services when possible to reduce operational overhead. Consider serverless database options for variable workloads.', 
 NOW() - INTERVAL '1 days 22 hours'),
((SELECT id FROM posts WHERE title='Database design patterns for scalable applications'),
 (SELECT id FROM users WHERE username='data_scientist'),
 'For analytics workloads, consider data warehousing patterns. Separate operational and analytical databases. Use ETL processes to maintain data consistency.', 
 NOW() - INTERVAL '1 days 21 hours'),
((SELECT id FROM posts WHERE title='Database design patterns for scalable applications'),
 (SELECT id FROM users WHERE username='backend_dev'),
 'Microservices often require database-per-service patterns. This adds complexity but provides better isolation and allows services to evolve independently.', 
 NOW() - INTERVAL '1 days 19 hours'),

/* Cloud providers thread (5 comments) */
((SELECT id FROM posts WHERE title='Cloud computing: AWS vs Azure vs Google Cloud'),
 (SELECT id FROM users WHERE username='cloud_architect'),
 'AWS has the most comprehensive service offering and largest market share. Azure integrates well with Microsoft ecosystem. Google Cloud has strong AI/ML and data analytics capabilities.', 
 NOW() - INTERVAL '1 days'),
((SELECT id FROM posts WHERE title='Cloud computing: AWS vs Azure vs Google Cloud'),
 (SELECT id FROM users WHERE username='startup_founder'),
 'For startups, consider the free tiers and pricing models. AWS has the most generous free tier, but Google Cloud often has better pricing for compute-intensive workloads.', 
 NOW() - INTERVAL '23 hours'),
((SELECT id FROM posts WHERE title='Cloud computing: AWS vs Azure vs Google Cloud'),
 (SELECT id FROM users WHERE username='devops_engineer'),
 'Multi-cloud strategies are becoming popular. Use the best service from each provider. However, this adds complexity and requires expertise in multiple platforms.', 
 NOW() - INTERVAL '22 hours'),
((SELECT id FROM posts WHERE title='Cloud computing: AWS vs Azure vs Google Cloud'),
 (SELECT id FROM users WHERE username='data_scientist'),
 'For ML/AI workloads, Google Cloud has the best tools and pre-trained models. TensorFlow and AutoML are industry-leading. AWS SageMaker is also excellent.', 
 NOW() - INTERVAL '21 hours'),
((SELECT id FROM posts WHERE title='Cloud computing: AWS vs Azure vs Google Cloud'),
 (SELECT id FROM users WHERE username='security_expert'),
 'All three providers have strong security offerings. The choice often depends on compliance requirements and existing enterprise relationships.', 
 NOW() - INTERVAL '20 hours'),

/* Testing strategies thread (5 comments) */
((SELECT id FROM posts WHERE title='Testing strategies for modern applications'),
 (SELECT id FROM users WHERE username='qa_engineer'),
 'Implement a testing pyramid: lots of unit tests, fewer integration tests, and minimal E2E tests. Automated testing is crucial for CI/CD pipelines.', 
 NOW() - INTERVAL '1 days'),
((SELECT id FROM posts WHERE title='Testing strategies for modern applications'),
 (SELECT id FROM users WHERE username='senior_engineer'),
 'Test-driven development (TDD) improves code quality and design. Write tests first to clarify requirements and catch bugs early in the development cycle.', 
 NOW() - INTERVAL '23 hours'),
((SELECT id FROM posts WHERE title='Testing strategies for modern applications'),
 (SELECT id FROM users WHERE username='tech_lead'),
 'Balance testing coverage with development speed. 100% coverage isn''t always necessary. Focus on critical paths and business logic.', 
 NOW() - INTERVAL '22 hours'),
((SELECT id FROM posts WHERE title='Testing strategies for modern applications'),
 (SELECT id FROM users WHERE username='frontend_dev'),
 'For frontend testing, use tools like Jest, React Testing Library, and Cypress. Visual regression testing is becoming important for UI consistency.', 
 NOW() - INTERVAL '21 hours'),
((SELECT id FROM posts WHERE title='Testing strategies for modern applications'),
 (SELECT id FROM users WHERE username='devops_engineer'),
 'Automate testing in your deployment pipeline. Use tools like GitHub Actions, Jenkins, or GitLab CI. Make testing a gate for production deployments.', 
 NOW() - INTERVAL '20 hours'),

/* Remote work thread (5 comments) */
((SELECT id FROM posts WHERE title='The impact of remote work on software development'),
 (SELECT id FROM users WHERE username='tech_lead'),
 'Remote work requires different management approaches. Focus on outcomes rather than hours worked. Use async communication and clear documentation.', 
 NOW() - INTERVAL '1 days'),
((SELECT id FROM posts WHERE title='The impact of remote work on software development'),
 (SELECT id FROM users WHERE username='product_manager'),
 'Product management has become more challenging with remote teams. We rely heavily on tools like Figma, Miro, and video conferencing for collaboration.', 
 NOW() - INTERVAL '23 hours'),
((SELECT id FROM posts WHERE title='The impact of remote work on software development'),
 (SELECT id FROM users WHERE username='senior_engineer'),
 'Code reviews and pair programming work differently remotely. We''ve adopted more async code reviews and use screen sharing for complex discussions.', 
 NOW() - INTERVAL '22 hours'),
((SELECT id FROM posts WHERE title='The impact of remote work on software development'),
 (SELECT id FROM users WHERE username='ui_designer'),
 'Design collaboration has evolved. We use Figma for real-time collaboration and Loom for design walkthroughs. The feedback process is more structured now.', 
 NOW() - INTERVAL '21 hours'),
((SELECT id FROM posts WHERE title='The impact of remote work on software development'),
 (SELECT id FROM users WHERE username='startup_founder'),
 'Remote work has expanded our talent pool globally. We can hire the best developers regardless of location, but time zone coordination becomes crucial.', 
 NOW() - INTERVAL '20 hours'),

/* Performance optimization thread (4 comments) */
((SELECT id FROM posts WHERE title='Performance optimization techniques for web apps'),
 (SELECT id FROM users WHERE username='frontend_dev'),
 'Start with the basics: lazy loading, code splitting, and image optimization. Use tools like Lighthouse to identify performance bottlenecks.', 
 NOW() - INTERVAL '1 days'),
((SELECT id FROM posts WHERE title='Performance optimization techniques for web apps'),
 (SELECT id FROM users WHERE username='senior_engineer'),
 'Caching is crucial. Implement proper HTTP caching headers, use CDNs for static assets, and consider service workers for offline functionality.', 
 NOW() - INTERVAL '23 hours'),
((SELECT id FROM posts WHERE title='Performance optimization techniques for web apps'),
 (SELECT id FROM users WHERE username='fullstack_dev'),
 'Database optimization is often overlooked. Use proper indexes, optimize queries, and consider read replicas for read-heavy applications.', 
 NOW() - INTERVAL '22 hours'),
((SELECT id FROM posts WHERE title='Performance optimization techniques for web apps'),
 (SELECT id FROM users WHERE username='cloud_architect'),
 'Use cloud-native performance features. CDNs, auto-scaling, and managed databases can significantly improve performance with minimal effort.', 
 NOW() - INTERVAL '21 hours'),

/* Mobile development thread (4 comments) */
((SELECT id FROM posts WHERE title='The future of mobile app development'),
 (SELECT id FROM users WHERE username='mobile_developer'),
 'Cross-platform frameworks are maturing rapidly. React Native and Flutter are viable alternatives to native development for most applications.', 
 NOW() - INTERVAL '1 days'),
((SELECT id FROM posts WHERE title='The future of mobile app development'),
 (SELECT id FROM users WHERE username='ui_designer'),
 'Design systems are crucial for mobile apps. Consistency across platforms improves user experience and reduces development time.', 
 NOW() - INTERVAL '23 hours'),
((SELECT id FROM posts WHERE title='The future of mobile app development'),
 (SELECT id FROM users WHERE username='tech_lead'),
 'Consider your target audience and app requirements. Native development still offers the best performance and access to platform-specific features.', 
 NOW() - INTERVAL '22 hours'),
((SELECT id FROM posts WHERE title='The future of mobile app development'),
 (SELECT id FROM users WHERE username='startup_founder'),
 'For startups, cross-platform development reduces costs and time to market. You can reach both iOS and Android users with a single codebase.', 
 NOW() - INTERVAL '21 hours'),

/* API design thread (3 comments) */
((SELECT id FROM posts WHERE title='API design best practices'),
 (SELECT id FROM users WHERE username='backend_dev'),
 'Follow RESTful principles, use proper HTTP status codes, and implement consistent error handling. Version your APIs from the start.', 
 NOW() - INTERVAL '1 days'),
((SELECT id FROM posts WHERE title='API design best practices'),
 (SELECT id FROM users WHERE username='frontend_dev'),
 'GraphQL is great for complex data requirements, but REST is simpler for most use cases. Choose based on your specific needs.', 
 NOW() - INTERVAL '23 hours'),
((SELECT id FROM posts WHERE title='API design best practices'),
 (SELECT id FROM users WHERE username='security_expert'),
 'Security should be built into API design. Implement proper authentication, rate limiting, and input validation. Use HTTPS everywhere.', 
 NOW() - INTERVAL '22 hours'),

/* Design systems thread (3 comments) */
((SELECT id FROM posts WHERE title='The role of design systems in modern development'),
 (SELECT id FROM users WHERE username='ui_designer'),
 'Design systems improve consistency and speed up development. They also help maintain brand identity across different platforms and applications.', 
 NOW() - INTERVAL '1 days'),
((SELECT id FROM posts WHERE title='The role of design systems in modern development'),
 (SELECT id FROM users WHERE username='frontend_dev'),
 'Component libraries like Material-UI and Ant Design reduce development time. Custom design systems offer more flexibility but require more maintenance.', 
 NOW() - INTERVAL '23 hours'),
((SELECT id FROM posts WHERE title='The role of design systems in modern development'),
 (SELECT id FROM users WHERE username='product_manager'),
 'Design systems improve user experience consistency and reduce design debt. They''re essential for scaling design across multiple products.', 
 NOW() - INTERVAL '22 hours'),

/* Career advice thread (3 comments) */
((SELECT id FROM posts WHERE title='Career advice for junior developers'),
 (SELECT id FROM users WHERE username='senior_engineer'),
 'Focus on fundamentals: data structures, algorithms, and system design. Learn one language deeply before jumping to others. Build projects and contribute to open source.', 
 NOW() - INTERVAL '1 days'),
((SELECT id FROM posts WHERE title='Career advice for junior developers'),
 (SELECT id FROM users WHERE username='tech_lead'),
 'Develop soft skills: communication, teamwork, and problem-solving. Technical skills are important, but collaboration skills will advance your career faster.', 
 NOW() - INTERVAL '23 hours'),
((SELECT id FROM posts WHERE title='Career advice for junior developers'),
 (SELECT id FROM users WHERE username='startup_founder'),
 'Network actively and build your personal brand. Contribute to the community through blogging, speaking, or mentoring. Your network is your net worth.', 
 NOW() - INTERVAL '22 hours');

/* OPTIONAL: auto-generate lightweight votes 
   (one up- or down-vote per user-post pair, random-ish)      */
INSERT INTO post_votes (post_id,user_id,vote_type)
SELECT p.id, u.id,
       CASE WHEN RANDOM() < 0.75 THEN 'upvote' ELSE 'downvote' END
FROM posts p
JOIN users u ON u.id % 7 = p.id % 7;   -- simple scatter pattern
